import React from "react";
import {
  FaBullhorn,
  FaEnvelope,
  FaGem,
  FaGithub,
  FaGlobe,
  FaImages,
  FaInstagram,
  FaLayerGroup,
  FaLightbulb,
  FaLinkedinIn,
  FaMagic,
  FaPaintBrush,
  FaPalette,
  FaPenNib,
  FaPrint,
  FaSearch,
  FaShareAlt,
  FaWhatsapp,
} from "react-icons/fa";
import {
  SiBootstrap,
  SiCanva,
  SiCss,
  SiElementor,
  SiFigma,
  SiGit,
  SiGoogleanalytics,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiNodedotjs,
  SiReact,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiWordpress,
} from "react-icons/si";
import { TbBrandAdobeIllustrator, TbBrandAdobePhotoshop, TbBrandAdobeXd } from "react-icons/tb";

const iconMap = {
  html: SiHtml5,
  css: SiCss,
  javascript: SiJavascript,
  typescript: SiTypescript,
  react: SiReact,
  vite: SiVite,
  tailwind: SiTailwindcss,
  bootstrap: SiBootstrap,
  wordpress: SiWordpress,
  elementor: SiElementor,
  git: SiGit,
  github: FaGithub,
  seo: FaSearch,
  analytics: SiGoogleanalytics,
  node: SiNodedotjs,
  mongodb: SiMongodb,
  xd: TbBrandAdobeXd,
  photoshop: TbBrandAdobePhotoshop,
  illustrator: TbBrandAdobeIllustrator,
  figma: SiFigma,
  canva: SiCanva,
  instagram: FaInstagram,
  whatsapp: FaWhatsapp,
  linkedin: FaLinkedinIn,
  email: FaEnvelope,
  portfolio: FaGlobe,
  graphic: FaPalette,
  poster: FaImages,
  brand: FaGem,
  social: FaShareAlt,
  campaign: FaBullhorn,
  typography: FaPenNib,
  layout: FaLayerGroup,
  color: FaPalette,
  story: FaLightbulb,
  print: FaPrint,
  logo: FaGem,
  event: FaImages,
  ad: FaBullhorn,
  discover: FaSearch,
  concept: FaLightbulb,
  design: FaMagic,
  deliver: FaPrint,
  brush: FaPaintBrush,
};

export default function IconBadge({ name, className = "" }) {
  const Icon = iconMap[name] || FaPalette;
  return (
    <span className={`icon-badge icon-${name} ${className}`.trim()} aria-hidden="true">
      <Icon />
    </span>
  );
}
